[package]
name = "client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
log.workspace = true
common.workspace = true
tokio.workspace = true
tokio.features = ["full"]
serde_json.workspace = true
ed25519-dalek = { workspace = true }
base64.workspace = true
x25519-dalek.workspace = true
