[package]
name = "RemoteHelperServer"
version = "1.0.0"
edition = "2024"

[dependencies]
nvml-wrapper = "0.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
sysinfo = "0.37.2"
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.10"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
common = { path = "common" }
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
rand = "0.8.5"
base64 = "0.22.1"
aes-gcm = "0.10.3"
pbkdf2 = "0.12.2"
hmac = "0.12.1"
sha2 = "0.10.9"
tracing-appender = "0.2.4"
tokio-rustls = "0.26.4"
rustls = "0.23.35"
rustls-pemfile = "2.2.0"
rcgen = "0.14.6"
anyhow = "1.0.100"
x25519-dalek = "2.0.1"


[workspace]
members = ["common", "client/src-tauri"]
