[web_panel]
enabled = true
local_port = 8088
# 可选：指定用于隧道的 frpc 可执行路径，缺省为 frpc.exe（需在 PATH 或工作目录）
frpc_exe_path = "E:\\UserData\\.Exe\\frpc.exe"
# 这里的 arg 是用于 Web 控制台的 frpc 隧道参数
frpc_args = ["-f", "84loylo19t7ut88mbr1afkyhynfbulg8:24958801"]
# Web 控制台访问密钥
authorized_keys = [
    "cD4nEfSeBQF+aWZZzLusNAcUthuq2uw4kZRlCPhkgkQ="
]
[[service]]
description = "Remote Desktop Access"
exe_path = "E:\\UserData\\.Exe\\frpc.exe"
args = ["-f", "84loylo19t7ut88mbr1afkyhynfbulg8:24539947"]
auto_start = false
allow_web_control = true

[[service]]
description = "SSH Access"
exe_path = "E:\\UserData\\.Exe\\frpc.exe"
args = ["-f", "84loylo19t7ut88mbr1afkyhynfbulg8:23371163"]
auto_start = false
allow_web_control = true

