[smtp]
enabled = false  # 是否启用邮件通知 (true: 启用, false: 禁用)
server = "smtp.qq.com"
username = "Hughsean@qq.com"
password = "lrgbulnorlvwbaii"
from = "Hughsean@qq.com"
to = "Hughsean.F@outlook.com"

[web_control]
enabled = true
local_port = 8080
# 这里的 arg 是用于 Web 控制台的 frpc 隧道参数
frpc_arg = "84loylo19t7ut88mbr1afkyhynfbulg8:24585311"
# Web 控制台访问密钥
auth_secret = "123456"

[[frpc]]
description = "Remote Desktop Access"
arg = "84loylo19t7ut88mbr1afkyhynfbulg8:24539947"
auto_start = false

[[frpc]]
description = "SSH Access"
arg = "84loylo19t7ut88mbr1afkyhynfbulg8:23371163"
auto_start = true
