[common]
user = 84loylo19t7ut88mbr1afkyhynfbulg8

sakura_mode = true
login_fail_exit = false

server_addr = frp-egg.com
server_port = 8088

proxy_protocol_version = v2

[Test]
# id = 24958801
type = tcp
local_ip = 127.0.0.1
local_port = 8088
remote_port = 28450
